### ISSUE TITLE
Top Level IO nodes getting renamed or trimmed in C++ emulator

### ISSUE THREAD

**Issue by sdtwigg** [ucb-bar/chisel#172]
If a top level IO node is not being used (not driving anything or driven by anything) then the C++ emulator trims it away. This is undesirable behavior as this causes handwritten C++ emulators to fail to compile and for the Scala tester to report superfluous errors.

A specific case is that I have a testbench that faithfully executes an accelerator interface with memory ports. However, some accelerators do not use part of the interface. The accelerator is configured to never send a valid request but the testbench still reports errors when it says it is ready to receive data from the part of the unused interface (that the backend prunes away). The main testbench still completes but the console is spammed with error messages.

Top level IO nodes should not be removed or renamed as the top level IO specification forms a contract between the hardware design and the verification testbench.

**Comment by ucbjrl** [comment]
This appears to have been resolved. Add a test case to ensure it stays resolved.
