### ISSUE TITLE
NullPointerException in Tester Doesn't Kill C++ Process

### ISSUE THREAD

**Issue by ffard-lbl** [ucb-bar/chisel#180]
When there is a NullPointerException in the Tester (which could be from a faultily written Tester), it obviously throws an exception and kills the test script. However, this does not kill the C++ Emulator, which continues to run indefinitely.

Should there be an exception, there should be an exception handler to kill all child processes.

**Comment by ucbjrl** [comment]
#678 duplicates this, and since we've closed that, I'm closing this.
