### ISSUE TITLE
My X's are still stalking me

### ISSUE THREAD

**Issue by ccelio** [ucb-bar/chisel#191]
So I have a terrible habit of not specifying the values to all of the fields in my Bundles.  It's expensive. Shoot me.

Problem is, our "randomize away our ex's" doesn't actually work - I still get X's in my waveforms. Uh oh.

So here's some code that breaks it.  Yes it throws some later tester error. Ignore it.  Look at the resulting *.v file. You should see a variable T3 that is being used to set my_reg_b on reset, but itself is NOT randomized.  Whoops.

````scala
import Chisel._


class myBundle extends Bundle
{
   val a = Bool()
   val b = Bool()
}

class HelloModule extends Module {

   val io = new Bundle 
   {
      val in = new myBundle().asInput
      val something = Bool(INPUT)
      val out = Bool(OUTPUT)
   }

   def NullMyBundle(): myBundle =
   {
      val bun = new myBundle
      bun.a := Bool(false)
      bun
   }
   
   val my_reg = Reg(init= NullMyBundle)
   
   when (io.something)
   {
      my_reg := io.in
   }  
   
   io.out := my_reg.a || my_reg.b
   
   
   printf("Hello World!\n")
}  

class HelloModuleTests(c: HelloModule) extends MapTester(c, Array(c.io)) {
    defTests {
        true 
    }   
}   

object hello {
    def main(args: Array[String]): Unit = {
        chiselMainTest(Array[String]("--backend", "v"),
            () => Module(new HelloModule())){c => new HelloModuleTests(c)}
    }       
}                                                                                     
````

There are other styles of initializing bundles that also fail, but this is the first test I can get up for it.

**Comment by ucbjrl** [comment]
This should be closed by pr #370.
