### ISSUE TITLE
--allocateOnlyNeededShadowRegisters breaks code, eats a register, may be getting dependence order wrong

### ISSUE THREAD

**Issue by ccelio** [ucb-bar/chisel#315]
I have the following piece of code:

````scala
val m2_req_uop = Reg(next=Reg(next=io.core.req.bits.uop))
````

Looking at the output in the waveform, I'm seeing "m2_req_uop.is_load" high ONE cycle after "io.core.req.bits.uop.is_load", not TWO as specified. 

Looking at the (broken) generated C++ code:
````cpp
R9992 = Top_BOOMTile_dcache__io_core_req_bits_uop_is_load;
 dat_t<1> Top_BOOMTile_dcache__m2_req_uop_is_load__shadow = R9992;
````

I am compiling Chisel with the arguments: "--debug --vcd --ioDebug --allocateOnlyNeededShadowRegisters".

If I remove "allocateOnlyNeededShadowRegisters", I get the following (working) C++:
```cpp
void Top_t::clock_hi ( dat_t<1> reset ) {
  ...
  dat_t<1> R9992__shadow = Top_BOOMTile_dcache__io_core_req_bits_uop_is_load;
  dat_t<1> Top_BOOMTile_dcache__m2_req_uop_is_load__shadow = R9992;
  ...
  R9992 = Top_BOOMTile_dcache__io_core_req_bits_uop_is_load;
  Top_BOOMTile_dcache__m2_req_uop_is_load = Top_BOOMTile_dcache__m2_req_uop_is_load__shadow;

```

**A couple of notes**:

* the R9992_shadow variable is unused in the working code.
* The working C++ code only works because R9992 is read first, *then* written to.
* The broken C++ code would work if the two lines of code were reversed.

**Comment by ucbjrl** [comment]
Regular testing since the previous fixes would seem to indicate this problem has been resolved.
