### ISSUE TITLE
Scala 2.9.x is broken under java 8

### ISSUE THREAD

**Issue by grebe** [ucb-bar/chisel#327]
I updated to Yosemite and installed java 8. Unfortunately, it seems that older versions of scala used by chisel don't play nice with java 8 (and it seems a bit odd that something is using scala 2.9.2).

I get an error on chisel/project/project/target/scala-2.9.2/sbt-0.12/classes...

[error] error while loading CharSequence, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
[error] (bad constant pool tag 18 at byte 10)
[error] error while loading Comparator, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar(java/util/Comparator.class)' is broken
[error] (bad constant pool tag 18 at byte 20)

What is involved in supporting java 8? Should I just give in and install java 6?

**Comment by ucbjrl** [comment]
Chisel currently uses sbt 0.13 and compiles with Scala versions 2.10 and 2.11.
