### ISSUE TITLE
Segmentation fault on "quit" (with Hello.scala from README.md)

### ISSUE THREAD

**Issue by cliffordwolf** [ucb-bar/chisel#363]
I'm in my first minutes of playing around with Chisel and I have zero Scala experience. Using the example build.sbt and Hello.scala from README.md:

    $ sbt run
    ....
    $ ./HelloModule 
    step 5
    PRINT 52 Hello World!
    Hello World!
    Hello World!
    Hello World!
    0
    quit
    Segmentation fault

I'm not even sure if "quit" is a valid command and I'm sure I am doing something very stupid here. But I think it should not segfault on any input..

Another thing: After Ctrl-D (sending EOF) I get an endless loop of

    Empty command: ''
    error
    Empty command: ''
    error
    Empty command: ''
    error

(This is with `libraryDependencies += "edu.berkeley.cs" %% "chisel" % "latest.release"`. I have not figured out yet how to use the git version of chisel. So sorry if this is already fixed in your git head..)

This is on Ubuntu 14.04.1 LTS.

**Comment by ucbjrl** [comment]
Thanks Clifford. PRs #365 and #366 should fix these issues.

To use a locally-cloned copy of chisel:

    % git clone https://github.com/ucb-bar/chisel.git
    % cd chisel
    % make publish-local

Replace the:

    libraryDependencies += "edu.berkeley.cs" %% "chisel" % "latest.release"

with

    libraryDependencies += "edu.berkeley.cs" %% "chisel" % "2.3-SNAPSHOT"

in build.sbt

**Comment by cliffordwolf** [comment]
Thanks!
