### ISSUE TITLE
Complete deprecation of (in Bits) !=(Bits) in favor of !==

### ISSUE THREAD

**Issue by sdtwigg** [ucb-bar/chisel#395]
As per discussion due to https://github.com/ucb-bar/chisel/commit/3242e1e4ebad9801e38305428e291005e1c88cae

Consider the following: (simplified)
```scala
def andexcept(exclude: Bool): Bool = andexcept(Some(exclude))
def andexcept(exclude: Option[Bool]): Bool = {
  val all_items = Vector(
    mod1.io.ready, mod2.io.ready, mod3.io.ready
  )
  val filtered_items = all_items.filter(candidate => exclude.map(_ != candidate).getOrElse(true))
  filtered_items.reduce(_&&_)
}
// ...
io.in.ready := andexcept(None)
mod1.io.valid := io.in.valid && andexcept(mod1.io.ready) 
mod2.io.valid := io.in.valid && andexcept(mod2.io.ready) 
mod3.io.valid := io.in.valid && andexcept(mod3.io.ready) 
```

This will not compile unless you adjust filtered_items to either:
```scala
val filtered_items = all_items.filter(candidate => exclude.map(_ ne candidate).getOrElse(true))
val filtered_items = exclude map (ex => all_items.filter(_ != ex)) getOrElse(all_items)
```

Also, at the basic level, != is defined as final in scala when applied against type AnyRef. It is peculiar that scala lets you do this override anyway. (I wonder if this is a 'bug' that will eventually be fixed in a later version of scala.) This leads to the strange behavior that elementary Chisel users will likely not have a problem. Then, intermediate Chisel users that try to leverage functional programming capabilities in scala will run into issues. A somewhat tedious advanced inspection will demonstrate the discrepancy (and likely to signal the user that Chisel isn't actually capable of properly integrating with other scala constructs).

Due to this, we must **introduce !== on Bits to replace != and mark the current != as deprecated to be removed by a later Chisel version (likely 3.0).** Fortunately, the actual removal will yield a scala type error for cases where the user neglected to convert. The only issue is if the user created an implicit conversion from scala.Boolean to Chisel.Bool; however, we have always advised against this conversion as it opens the user up to many other possible bugs (in particular, bad when statements where == is used instead of ===). Furthermore, this syntax change more closely matches what other DSLs implemented in scala do.

**Comment by ucbjrl** [comment]
Resolved by  28f98d81bbce1e5ae70c9a667e4b51b03dd078d8
