### ISSUE TITLE
C++ emulator error 2

### ISSUE THREAD

**Issue by richardarase** [ucb-bar/chisel#436]
richard@richard-HP-ENVY-15-Notebook-PC:~/Rocket/rocket-chip/emulator$ make -j4 run
make -C /home/richard/Rocket/rocket-chip/riscv-tools/riscv-tests/isa/ rv64ui-p-add.hex
make[1]: Entering directory `/home/richard/Rocket/rocket-chip/riscv-tools/riscv-tests/isa'
riscv64-unknown-elf-gcc  -static -fpic -fvisibility=hidden -nostdlib -nostartfiles -Wa,-march=RVIMAFDXhwacha -I./../env/p -I./macros/scalar -T./../env/p/link.ld rv64ui/add.S -o rv64ui-p-add
make[1]: riscv64-unknown-elf-gcc: Command not found
make[1]: *** [rv64ui-p-add] Error 127
make[1]: Leaving directory `/home/richard/Rocket/rocket-chip/riscv-tools/riscv-tests/isa'
make: *** [/home/richard/Rocket/rocket-chip/riscv-tools/riscv-tests/isa/rv64ui-p-add.hex] Error 2
richard@richard-HP-ENVY-15-Notebook-PC:~/Rocket/rocket-chip/emulator$

**Comment by ccelio** [comment]
```
make[1]: riscv64-unknown-elf-gcc: Command not found make
```

As your error message says, you are missing the executable `riscv64-uknown-elf-gcc`. You need to install the riscv-tools properly, as described in the README (https://github.com/riscv/riscv-tools).
