### ISSUE TITLE
Chisel Tutorial uses UFix instead of UInt

### ISSUE THREAD

**Issue by ccelio** [ucb-bar/chisel#446]
https://chisel.eecs.berkeley.edu/2.0.6/chisel-tutorial.pdf

The finite state machine example (as well as other places) use UFix instead of UInt.

Found here (http://stackoverflow.com/questions/31227369/chisel-switch-statement-doesnt-appear-to-work-in-manner-outlined-in-official-tu).

**Comment by ccelio** [comment]
I also noticed that the switch/is construct fails to compile if the "is" doesn't start on its own line.

**Comment by ucbjrl** [comment]
Should be resolved by commit b2c5674
