### ISSUE TITLE
Dbl comparison operations

### ISSUE THREAD

**Issue by andreaTP** [ucb-bar/chisel#516]
I'm facing a problem using Dbl numbers.
```<``` retrives ```java.lang.AssertionError: assertion failed: operator d< unsupported```
```<=``` looks always ```true```
```>``` looks always ```false```
```>=``` looks always ```true```

Any idea?

**Comment by ucbjrl** [comment]
Indeed the operator "d<" was missing. PR #517 (commit 2ff4e4c) should fix this and add DoubleSuite tests that verify Dbl comparisons.
