### ISSUE TITLE
Error message reporting strategy

### ISSUE THREAD

**Issue by doughnit** [ucb-bar/chisel#535]
The current scheme for reporting Chisel errors is, essentially, dump a stack trace, analyze it, and (somewhat arbitrarily) determine which line contains the entry point from 'user' code. That information is then added to an errors list (along with some form of error message) to then be dumped later.

First, the dumping of the error message is done at the wrong place. An error that occurs during elaboration time is dumped after some sort of naming backend pass so it is not immediately clear that the error was related to a user mistake elaborating the graph.

Second, the line determination is often wrong (too often declaring the error is in in some java code written by Sun). Even when correct, the loss of full stack trace information can make debugging very tedious as it is occasionally hard to determine the exact code path in a generator that led to the improper elaboration.

**Comment by ucbjrl** [comment]
Closed by #593, but feel free to re-open (with example code or a pull request).
