### ISSUE TITLE
Module debug for aggregates

### ISSUE THREAD

**Issue by shunshou** [ucb-bar/chisel#556]
I noticed that you have to add elements in a Vec individually with the debug function. Something like :
def debug(data: Aggregate) {
    data.flatten.map(x => x._2) map (debug(_))
 }
would make forced inclusion of Vecs, Complex, etc. for debugging at intermediate design stages less tedious... I have that in my extension of Module.scala, but it's be nice to just add this directly...

**Comment by ucbjrl** [comment]
Closed by #608
