### ISSUE TITLE
C simulation left running if exception in tester

### ISSUE THREAD

**Issue by da-steve101** [ucb-bar/chisel#678]
Running the following code produces an index out of bounds in the Tester.
It also means the C simulation is not terminated meaning it has to be manually killed.
```scala
class MyMod extends Module {
  val io = new Bundle {
    val a = UInt( INPUT, 4 )
    val b = UInt(OUTPUT, 4)
  }
  io.b := io.a
}

class MyModTests( c : MyMod ) extends Tester {
  val ary = Array(1, 2, 3)
  println("Cause exception = " + ary(4))
}
```

**Comment by JackDavidson** [comment]
just a note, this is the same issue as [https://github.com/ucb-bar/chisel/issues/180](https://github.com/ucb-bar/chisel/issues/180)
