### ISSUE TITLE
Q: "make getting-started" fails

### ISSUE THREAD

**Issue by omerfirmak** [ucb-bar/chisel#725]
I am following the instructions in the following link.

https://chisel.eecs.berkeley.edu/2.2.0/getting-started.html

I run the "make Parity.out" command with success. But "make getting-started" fails no matter how many times i try it. I have seen at most 4 of the 16 tests pass.

I have gcc 6.1.1 , openjdk 8 on a Arch Linux system.

**Comment by ucbjrl** [comment]
> On Aug 18, 2016, at 1:16 AM, Omer Faruk IRMAK <notifications@github.com> wrote:
> 
> I am following the instructions in the following link.
> 
> https://chisel.eecs.berkeley.edu/2.2.0/getting-started.html
> 
> I run the "make Parity.out" command with success. But "make getting-started" fails no matter how many times i try it. I have seen at most 4 of the 16 tests pass.
> 
> I have gcc 6.1.1 , openjdk 8 on a Arch Linux system.
> 

Are you editing the problem files to add the missing code elements?

They will fail until you do so.

**Comment by omerfirmak** [comment]
@ucbjrl 
No, I haven't edited anything so far.
Can you point me to a link to help me with those?

**Comment by ucbjrl** [comment]
> On Aug 18, 2016, at 8:38 AM, Omer Faruk IRMAK <notifications@github.com> wrote:
> 
> @ucbjrl 
> No, I haven't edited anything so far.
> Can you point me to a link to help me with those?
> 

Download and read the Chisel 2.2 Tutorial - https://chisel.eecs.berkeley.edu/2.2.0/chisel-tutorial.pdf.
Read the individual chisel-tutorial/problems Scala files and follow the instructions in the comments.

**Comment by omerfirmak** [comment]
Makes sense now :)
Thanks.
