### ISSUE TITLE
Attaching Analog(X.W) to several Analog(1.W)

### ISSUE THREAD

**Issue by mwachs5** [ucb-bar/chisel#748]
Is there *no* way to connect Analog(x.W) to e.g. a Vec(x, Analog(1.W))?

I would want to use Vec(x, Analog(1.W)) everywhere, except when I connect to a black-box which actually has

```
inout [2:0] foo;
```

then I I need to use 
```
val foo = Analog(3.W)
```
instead of 
```
val foo = Vec(3, Analog(1.W))
```

**Comment by edwardcwang** [comment]
Since this looks like a chisel3 question, I've migrated it to https://github.com/freechipsproject/chisel3/issues/784, but let me know if that is a mistake.
